# Generated by Django 4.1.13 on 2024-02-22 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_post_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="categories",
        ),
    ]
