# Generated by Django 4.1.13 on 2024-02-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_alter_post_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("DR", "Draft"), ("CR", "Created")], default="DF", max_length=2
            ),
        ),
    ]
